var styleElement = document.createElement('style');
styleElement.innerHTML = ` .MConZz{position:fixed;top:0;left:0;right:0;bottom:0;z-index:9999999999;width:100%;height:100%;background: linear-gradient(to bottom, rgba(17,17,17,0.9), rgba(34,34,34,0.9)); backdrop-filter:blur(5px);display:none;place-items:center; transition:0.2s ease}     .MConZzc{/*background-image: linear-gradient(to right, black 70%, #1A1A1A 100%);*/background: linear-gradient(to bottom, #050505, #222); width:80%;max-width:400px;min-height:60px;height:auto;padding:10px;border-radius:21px;margin:0px 20px; display:grid;place-items: center;border:2px solid #020e1a}     .MConZz_Img{width:100%;height:85%;display:grid;place-items:center;margin:0;border:0px solid #000;overflow:} .MConZz_Img img{width:50%;height:95%; position:relative;border:0px solid #fff;margin:-5% 0px 0% 0px;border-radius:500px;mix-blend-mode: lighten;padding:5px 10px; background:#000;} .MConZz_Hed p{margin:0% 0 -0% 0;font-weight:1000;font-size:30px;letter-spacing: 2px;color: #0095FF; background:rgba(255,255,255,0); border-radius:50px;padding:4px 8px;} .MConZz_Tit{font-weight:500;font-size:20px;color:#fff;letter-spacing:1.3px;margin:0px 0 5px 0;/*background:linear-gradient(to right, #fff 80%, black 100%);-webkit-background-clip: text; -webkit-text-stroke:0.4px transparent;*/font-family: 'Poppins', sans-serif;} .MConZz_Btn{width:100%;padding:20px;border:0px solid #000;display:flex;justify-content:space-between} .MConZz_Btn button{box-shadow: rgba(149, 157, 165, 0.4) 0px 8px 17px;outline:none;border:1px solid #000;padding:10px 20px;border-radius:13px;width:100px;font-weight:600;font-size:17px;color:#fff; transition:0.2s ease;transition: transform 0.3s;/*background-image: radial-gradient( circle farthest-corner at 90% 90%,  rgba(166,239,253,1) 0%, rgba(97,186,255,1) 99.1% )*/;background: linear-gradient(to bottom, #111, #222); } .MConZz_Btn button:hover{transform: scale(1.1);background: linear-gradient(to bottom, #111, #222); } `;
document.head.appendChild(styleElement);
var divElement = document.createElement('div');
divElement.innerHTML = ` <div class="MConZz" id="MConZzX">  <div class="MConZzc">        <!-- <div class="MConZz_Hed">      <p>Exit</p>    </div>    -->    <div class="MConZz_Img"> <img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi3xkTq-tOALo-L6DklaIFsF-BY3NFmQd9bLgofhFfR7bOAxXAvJ5aAr9sTBD1miILlF2qBYoif2ULbNL2KWAua36BSd-1Adkhr1607i_khXPXvbFAO9Q7oUhJKrdIBL4vAdg5661leJ04I4wEcw1BmKVjfliLLjVUIZAytF4SBKm3tCoQ71eyyCVEYMr4/s602/20230916_115337.gif" alt="">    </div>       <div class="MConZz_Tit"> <small>"Do want to exit the app?"</small>          </div>    <div class="MConZz_Btn">      <button onclick="ACncl()" style="background:#408cff">Cancel</button>        <button onclick="AExt()">Exit</button>           </div>  </div>     </div>  `;
document.body.appendChild(divElement);
var scriptElement = document.createElement('script');
scriptElement.innerHTML = ` function shwClAp(){var videos = document.getElementsByTagName("video");   for (var i = 0; i < videos.length; i++) {     videos[i].pause();   }; document.getElementById("MConZzX").style.display = "grid"; document.body.style.overflow = "hidden";} function AExt(){     if(window.AppInventor){         window.AppInventor.setWebViewString("AExt");     } }  function ACncl(){     var MConZz = document.getElementById("MConZzX");     MConZz.style.display = "none";document.body.style.overflow = "";} `;
document.body.appendChild(scriptElement);
